-- MySQL Script generated by MySQL Workbench
-- Tue Oct 10 21:52:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_universidade
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `db_universidade` DEFAULT CHARACTER SET utf8 ;
USE `db_universidade` ;

-- -----------------------------------------------------
-- Table `db_universidade`.`tb_candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_candidato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `historico_escolar` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `dt_candidatura` DATE NOT NULL,
  `resultado_avaliacao` INT NOT NULL DEFAULT 0,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`tb_equipe_admissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_equipe_admissoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `membro_equipe` VARCHAR(300) NOT NULL,
  `dt_cadastro` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`tb_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `duracao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`tb_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `nome_responsavel` VARCHAR(200) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `dt_matricula` DATE NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tb_curso_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_curso_id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_tb_aluno_tb_curso1_idx` (`tb_curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_aluno_tb_curso1`
    FOREIGN KEY (`tb_curso_id`)
    REFERENCES `db_universidade`.`tb_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`tb_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `dt_contrato` DATE NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `especializacao` VARCHAR(45) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`tb_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `horario_aula` VARCHAR(45) NOT NULL,
  `dia_semana` VARCHAR(45) NOT NULL,
  `tb_professor_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_professor_id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tb_disciplina_tb_professor1_idx` (`tb_professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_disciplina_tb_professor1`
    FOREIGN KEY (`tb_professor_id`)
    REFERENCES `db_universidade`.`tb_professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`tb_atividades_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_atividades_extra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `dt_criacao` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`td_administracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`td_administracao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `membros` VARCHAR(300) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `tb_atividades_extra_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_atividades_extra_id`),
  INDEX `fk_td_administracao_tb_atividades_extra1_idx` (`tb_atividades_extra_id` ASC) VISIBLE,
  CONSTRAINT `fk_td_administracao_tb_atividades_extra1`
    FOREIGN KEY (`tb_atividades_extra_id`)
    REFERENCES `db_universidade`.`tb_atividades_extra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`tb_aluno_has_tb_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_aluno_has_tb_disciplina` (
  `tb_aluno_id` INT NOT NULL,
  `tb_aluno_tb_curso_id` INT NOT NULL,
  `tb_disciplina_id` INT NOT NULL,
  PRIMARY KEY (`tb_aluno_id`, `tb_aluno_tb_curso_id`, `tb_disciplina_id`),
  INDEX `fk_tb_aluno_has_tb_disciplina_tb_disciplina1_idx` (`tb_disciplina_id` ASC) VISIBLE,
  INDEX `fk_tb_aluno_has_tb_disciplina_tb_aluno1_idx` (`tb_aluno_id` ASC, `tb_aluno_tb_curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_aluno_has_tb_disciplina_tb_aluno1`
    FOREIGN KEY (`tb_aluno_id` , `tb_aluno_tb_curso_id`)
    REFERENCES `db_universidade`.`tb_aluno` (`id` , `tb_curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluno_has_tb_disciplina_tb_disciplina1`
    FOREIGN KEY (`tb_disciplina_id`)
    REFERENCES `db_universidade`.`tb_disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`tb_aluno_has_tb_atividades_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_aluno_has_tb_atividades_extra` (
  `tb_aluno_id` INT NOT NULL,
  `tb_aluno_tb_curso_id` INT NOT NULL,
  `tb_atividades_extra_id` INT NOT NULL,
  PRIMARY KEY (`tb_aluno_id`, `tb_aluno_tb_curso_id`, `tb_atividades_extra_id`),
  INDEX `fk_tb_aluno_has_tb_atividades_extra_tb_atividades_extra1_idx` (`tb_atividades_extra_id` ASC) VISIBLE,
  INDEX `fk_tb_aluno_has_tb_atividades_extra_tb_aluno1_idx` (`tb_aluno_id` ASC, `tb_aluno_tb_curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_aluno_has_tb_atividades_extra_tb_aluno1`
    FOREIGN KEY (`tb_aluno_id` , `tb_aluno_tb_curso_id`)
    REFERENCES `db_universidade`.`tb_aluno` (`id` , `tb_curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluno_has_tb_atividades_extra_tb_atividades_extra1`
    FOREIGN KEY (`tb_atividades_extra_id`)
    REFERENCES `db_universidade`.`tb_atividades_extra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`tb_tipo_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_tipo_avaliacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_avaliacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_universidade`.`tb_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_universidade`.`tb_avaliacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dt_avaliacao` DATE NOT NULL,
  `tb_candidato_id` INT NOT NULL,
  `tb_equipe_admissoes_id` INT NOT NULL,
  `tb_tipo_avaliacao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_candidato_id`, `tb_equipe_admissoes_id`, `tb_tipo_avaliacao_id`),
  INDEX `fk_tb_avaliacao_tb_candidato1_idx` (`tb_candidato_id` ASC) VISIBLE,
  INDEX `fk_tb_avaliacao_tb_equipe_admissoes1_idx` (`tb_equipe_admissoes_id` ASC) VISIBLE,
  INDEX `fk_tb_avaliacao_tb_tipo_avaliacao1_idx` (`tb_tipo_avaliacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_avaliacao_tb_candidato1`
    FOREIGN KEY (`tb_candidato_id`)
    REFERENCES `db_universidade`.`tb_candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_avaliacao_tb_equipe_admissoes1`
    FOREIGN KEY (`tb_equipe_admissoes_id`)
    REFERENCES `db_universidade`.`tb_equipe_admissoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_avaliacao_tb_tipo_avaliacao1`
    FOREIGN KEY (`tb_tipo_avaliacao_id`)
    REFERENCES `db_universidade`.`tb_tipo_avaliacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
